"""empty message

Revision ID: 3343fc56c0aa
Revises: 
Create Date: 2024-09-26 20:49:53.011104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3343fc56c0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinates')
    op.drop_table('mission')
    op.drop_table('target_details')
    op.drop_table('location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.INTEGER(), server_default=sa.text("nextval('location_location_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('location_id', name='location_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('target_details',
    sa.Column('target_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_priority', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coordinates_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.coordinates_id'], name='target_details_coordinates_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='target_details_location_id_fkey'),
    sa.PrimaryKeyConstraint('target_id', name='target_details_pkey')
    )
    op.create_table('mission',
    sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mission_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('theater_of_operations', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('air_force', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('aircraft_series', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('callsign', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mission_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('takeoff_base', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('takeoff_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('takeoff_latitude', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('takeoff_longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_priority', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('target_latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('target_longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('altitude_hundreds_of_feet', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('airborne_aircraft', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('attacking_aircraft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bombing_aircraft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aircraft_returned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aircraft_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aircraft_damaged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aircraft_lost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_explosives', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('high_explosives_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('high_explosives_weight_pounds', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('high_explosives_weight_tons', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('incendiary_devices', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('incendiary_devices_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('incendiary_devices_weight_pounds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('incendiary_devices_weight_tons', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fragmentation_devices', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fragmentation_devices_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fragmentation_devices_weight_pounds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fragmentation_devices_weight_tons', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_weight_pounds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_weight_tons', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('time_over_target', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('bomb_damage_assessment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('mission_id', name='mission_pkey')
    )
    op.create_table('coordinates',
    sa.Column('coordinates_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('coordinates_id', name='coordinates_pkey')
    )
    # ### end Alembic commands ###
